#version: '3.8'
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: always #no, on-failure , always(default), unless-stopped 
include:
  - /home/vboxuser/VSC/practice5/shvirtd-example-python/proxy.yaml
  
services:
  web:
    build:

      context: .

      dockerfile: Dockerfile.python

    #command: python main.py
    networks:
      backend:
        ipv4_address: 172.20.0.5
    <<: [*env_file, *restart]
    environment:
      - MYSQL_DB_NAME=virtd
      - MYSQL_DB_USER=app
      - MYSQL_DB_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB_HOST=mysql

    #volumes:
    #  - "main.py:/app"


    depends_on:
      - db

  db:
    image: mysql:8
    networks: 
      backend:
        ipv4_address: 172.20.0.10
    <<: [*env_file, *restart]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=virtd
      - MYSQL_USER=app
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"

    #command: 

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: nginx.dockerfile
  #   depends_on: ["db"]
  #   ports: ["80:80"]
  #   networks: ["backend"]